[32mINFO[0m:     [30-03-2024 15:01:36] Set chroma_server_nofile to 65535
[32mINFO[0m:     [30-03-2024 15:01:36] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [30-03-2024 15:01:36] Starting component System
[36mDEBUG[0m:    [30-03-2024 15:01:36] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [30-03-2024 15:01:36] Starting component SimpleAssignmentPolicy
[36mDEBUG[0m:    [30-03-2024 15:01:36] Starting component SqliteDB
[36mDEBUG[0m:    [30-03-2024 15:01:36] Starting component QuotaEnforcer
[36mDEBUG[0m:    [30-03-2024 15:01:36] Starting component Posthog
[36mDEBUG[0m:    [30-03-2024 15:01:36] Starting component LocalSegmentManager
[36mDEBUG[0m:    [30-03-2024 15:01:36] Starting component SegmentAPI
[32mINFO[0m:     [30-03-2024 15:01:36] Started server process [[36m90328[0m]
[32mINFO[0m:     [30-03-2024 15:01:36] Waiting for application startup.
[32mINFO[0m:     [30-03-2024 15:01:36] Application startup complete.
[32mINFO[0m:     [30-03-2024 15:01:36] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [30-03-2024 15:02:55] ::1:58466 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:02:55] ::1:58466 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:02:55] ::1:58467 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:02:55] ::1:58467 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:03:12] ::1:58467 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[36mDEBUG[0m:    [30-03-2024 15:03:12] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [30-03-2024 15:03:12] ::1:58467 - "POST /api/v1/collections/54e8cb46-e87e-4642-971f-53cf04603254/add HTTP/1.1" 201
[32mINFO[0m:     [30-03-2024 15:03:12] ::1:58467 - "POST /api/v1/collections/54e8cb46-e87e-4642-971f-53cf04603254/query HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:07:12] ::1:58489 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:07:12] ::1:58489 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:07:12] ::1:58490 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:07:12] ::1:58490 - "GET /api/v1/collections/new_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:07:13] ::1:58490 - "POST /api/v1/collections/54e8cb46-e87e-4642-971f-53cf04603254/query HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:08:37] ::1:58497 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:08:37] ::1:58497 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:08:37] ::1:58498 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[31mERROR[0m:    [30-03-2024 15:08:37] Collection collection does not exist.
Traceback (most recent call last):
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 82, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/mrpurtas/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 96, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/chromadb/auth/fastapi.py", line 241, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 440, in get_collection
    return self._api.get_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/mrpurtas/Desktop/Generative_AI/module6/rag/venv/lib/python3.11/site-packages/chromadb/api/segment.py", line 261, in get_collection
    raise ValueError(f"Collection {name} does not exist.")
ValueError: Collection collection does not exist.
[32mINFO[0m:     [30-03-2024 15:08:37] ::1:58498 - "GET /api/v1/collections/collection?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [30-03-2024 15:08:53] ::1:58502 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:08:53] ::1:58502 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:08:53] ::1:58503 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:08:53] ::1:58503 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:08:55] ::1:58503 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[36mDEBUG[0m:    [30-03-2024 15:08:55] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [30-03-2024 15:08:55] ::1:58503 - "POST /api/v1/collections/72ad0363-b658-4f81-8db1-7c0d60180358/add HTTP/1.1" 201
[32mINFO[0m:     [30-03-2024 15:08:55] ::1:58503 - "POST /api/v1/collections/72ad0363-b658-4f81-8db1-7c0d60180358/query HTTP/1.1" 200
[32mINFO[0m:     [30-03-2024 15:13:49] Shutting down
[32mINFO[0m:     [30-03-2024 15:13:49] Waiting for application shutdown.
[36mDEBUG[0m:    [30-03-2024 15:13:49] Stopping component System
[36mDEBUG[0m:    [30-03-2024 15:13:49] Stopping component SegmentAPI
[36mDEBUG[0m:    [30-03-2024 15:13:49] Stopping component PersistentLocalHnswSegment
[36mDEBUG[0m:    [30-03-2024 15:13:49] Stopping component PersistentLocalHnswSegment
[36mDEBUG[0m:    [30-03-2024 15:13:49] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [30-03-2024 15:13:49] Stopping component Posthog
[36mDEBUG[0m:    [30-03-2024 15:13:49] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [30-03-2024 15:13:49] Stopping component SqliteDB
[36mDEBUG[0m:    [30-03-2024 15:13:49] Stopping component SimpleAssignmentPolicy
[36mDEBUG[0m:    [30-03-2024 15:13:49] Stopping component OpenTelemetryClient
[32mINFO[0m:     [30-03-2024 15:13:49] Application shutdown complete.
[32mINFO[0m:     [30-03-2024 15:13:49] Finished server process [[36m90328[0m]
